// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

public final class AccountProto {
  private AccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateKeygenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateKeygenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateKeygenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateKeygenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateSignatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateSignatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenerateSignatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenerateSignatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\"7\n\025GenerateKeygenRequest" +
      "\022\016\n\006number\030\001 \001(\r\022\016\n\006method\030\002 \001(\t\"/\n\026Gene" +
      "rateKeygenResponse\022\025\n\rpublicKeyList\030\001 \003(" +
      "\t\"-\n\030GenerateSignatureRequest\022\021\n\tpublicK" +
      "ey\030\001 \001(\t\".\n\031GenerateSignatureResponse\022\021\n" +
      "\tsignature\030\001 \001(\t2\234\001\n\007Account\022C\n\016Generate" +
      "Keygen\022\026.GenerateKeygenRequest\032\027.Generat" +
      "eKeygenResponse\"\000\022L\n\021GenerateSignature\022\031" +
      ".GenerateSignatureRequest\032\032.GenerateSign" +
      "atureResponse\"\000B(\n\026xyz.dapplink.iface.li" +
      "bB\014AccountProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GenerateKeygenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GenerateKeygenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateKeygenRequest_descriptor,
        new java.lang.String[] { "Number", "Method", });
    internal_static_GenerateKeygenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GenerateKeygenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateKeygenResponse_descriptor,
        new java.lang.String[] { "PublicKeyList", });
    internal_static_GenerateSignatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GenerateSignatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateSignatureRequest_descriptor,
        new java.lang.String[] { "PublicKey", });
    internal_static_GenerateSignatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GenerateSignatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenerateSignatureResponse_descriptor,
        new java.lang.String[] { "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
