// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public interface ExportPublicKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dapplink.wallet.ExportPublicKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_token = 1;</code>
   * @return The consumerToken.
   */
  java.lang.String getConsumerToken();
  /**
   * <code>string consumer_token = 1;</code>
   * @return The bytes for consumerToken.
   */
  com.google.protobuf.ByteString
      getConsumerTokenBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>uint64 number = 3;</code>
   * @return The number.
   */
  long getNumber();
}
