// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

/**
 * Protobuf type {@code dapplink.wallet.ExportPublicKeyResponse}
 */
public final class ExportPublicKeyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dapplink.wallet.ExportPublicKeyResponse)
    ExportPublicKeyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExportPublicKeyResponse.newBuilder() to construct.
  private ExportPublicKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExportPublicKeyResponse() {
    code_ = "";
    msg_ = "";
    publicKey_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExportPublicKeyResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return xyz.dapplink.iface.lib.WalletProto.internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return xyz.dapplink.iface.lib.WalletProto.internal_static_dapplink_wallet_ExportPublicKeyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            xyz.dapplink.iface.lib.ExportPublicKeyResponse.class, xyz.dapplink.iface.lib.ExportPublicKeyResponse.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msg_ = "";
  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<xyz.dapplink.iface.lib.PublicKey> publicKey_;
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  @java.lang.Override
  public java.util.List<xyz.dapplink.iface.lib.PublicKey> getPublicKeyList() {
    return publicKey_;
  }
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends xyz.dapplink.iface.lib.PublicKeyOrBuilder> 
      getPublicKeyOrBuilderList() {
    return publicKey_;
  }
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  @java.lang.Override
  public int getPublicKeyCount() {
    return publicKey_.size();
  }
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  @java.lang.Override
  public xyz.dapplink.iface.lib.PublicKey getPublicKey(int index) {
    return publicKey_.get(index);
  }
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  @java.lang.Override
  public xyz.dapplink.iface.lib.PublicKeyOrBuilder getPublicKeyOrBuilder(
      int index) {
    return publicKey_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
    }
    for (int i = 0; i < publicKey_.size(); i++) {
      output.writeMessage(3, publicKey_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
    }
    for (int i = 0; i < publicKey_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, publicKey_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof xyz.dapplink.iface.lib.ExportPublicKeyResponse)) {
      return super.equals(obj);
    }
    xyz.dapplink.iface.lib.ExportPublicKeyResponse other = (xyz.dapplink.iface.lib.ExportPublicKeyResponse) obj;

    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (!getPublicKeyList()
        .equals(other.getPublicKeyList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    if (getPublicKeyCount() > 0) {
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKeyList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(xyz.dapplink.iface.lib.ExportPublicKeyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dapplink.wallet.ExportPublicKeyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dapplink.wallet.ExportPublicKeyResponse)
      xyz.dapplink.iface.lib.ExportPublicKeyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.dapplink.iface.lib.WalletProto.internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.dapplink.iface.lib.WalletProto.internal_static_dapplink_wallet_ExportPublicKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.dapplink.iface.lib.ExportPublicKeyResponse.class, xyz.dapplink.iface.lib.ExportPublicKeyResponse.Builder.class);
    }

    // Construct using xyz.dapplink.iface.lib.ExportPublicKeyResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = "";
      msg_ = "";
      if (publicKeyBuilder_ == null) {
        publicKey_ = java.util.Collections.emptyList();
      } else {
        publicKey_ = null;
        publicKeyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return xyz.dapplink.iface.lib.WalletProto.internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor;
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.ExportPublicKeyResponse getDefaultInstanceForType() {
      return xyz.dapplink.iface.lib.ExportPublicKeyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.ExportPublicKeyResponse build() {
      xyz.dapplink.iface.lib.ExportPublicKeyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.ExportPublicKeyResponse buildPartial() {
      xyz.dapplink.iface.lib.ExportPublicKeyResponse result = new xyz.dapplink.iface.lib.ExportPublicKeyResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(xyz.dapplink.iface.lib.ExportPublicKeyResponse result) {
      if (publicKeyBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          publicKey_ = java.util.Collections.unmodifiableList(publicKey_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.publicKey_ = publicKey_;
      } else {
        result.publicKey_ = publicKeyBuilder_.build();
      }
    }

    private void buildPartial0(xyz.dapplink.iface.lib.ExportPublicKeyResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msg_ = msg_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof xyz.dapplink.iface.lib.ExportPublicKeyResponse) {
        return mergeFrom((xyz.dapplink.iface.lib.ExportPublicKeyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(xyz.dapplink.iface.lib.ExportPublicKeyResponse other) {
      if (other == xyz.dapplink.iface.lib.ExportPublicKeyResponse.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (publicKeyBuilder_ == null) {
        if (!other.publicKey_.isEmpty()) {
          if (publicKey_.isEmpty()) {
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePublicKeyIsMutable();
            publicKey_.addAll(other.publicKey_);
          }
          onChanged();
        }
      } else {
        if (!other.publicKey_.isEmpty()) {
          if (publicKeyBuilder_.isEmpty()) {
            publicKeyBuilder_.dispose();
            publicKeyBuilder_ = null;
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000004);
            publicKeyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPublicKeyFieldBuilder() : null;
          } else {
            publicKeyBuilder_.addAllMessages(other.publicKey_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              msg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              xyz.dapplink.iface.lib.PublicKey m =
                  input.readMessage(
                      xyz.dapplink.iface.lib.PublicKey.parser(),
                      extensionRegistry);
              if (publicKeyBuilder_ == null) {
                ensurePublicKeyIsMutable();
                publicKey_.add(m);
              } else {
                publicKeyBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object code_ = "";
    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      msg_ = getDefaultInstance().getMsg();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<xyz.dapplink.iface.lib.PublicKey> publicKey_ =
      java.util.Collections.emptyList();
    private void ensurePublicKeyIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        publicKey_ = new java.util.ArrayList<xyz.dapplink.iface.lib.PublicKey>(publicKey_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        xyz.dapplink.iface.lib.PublicKey, xyz.dapplink.iface.lib.PublicKey.Builder, xyz.dapplink.iface.lib.PublicKeyOrBuilder> publicKeyBuilder_;

    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public java.util.List<xyz.dapplink.iface.lib.PublicKey> getPublicKeyList() {
      if (publicKeyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(publicKey_);
      } else {
        return publicKeyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public int getPublicKeyCount() {
      if (publicKeyBuilder_ == null) {
        return publicKey_.size();
      } else {
        return publicKeyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public xyz.dapplink.iface.lib.PublicKey getPublicKey(int index) {
      if (publicKeyBuilder_ == null) {
        return publicKey_.get(index);
      } else {
        return publicKeyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder setPublicKey(
        int index, xyz.dapplink.iface.lib.PublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.set(index, value);
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder setPublicKey(
        int index, xyz.dapplink.iface.lib.PublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.set(index, builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder addPublicKey(xyz.dapplink.iface.lib.PublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder addPublicKey(
        int index, xyz.dapplink.iface.lib.PublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePublicKeyIsMutable();
        publicKey_.add(index, value);
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder addPublicKey(
        xyz.dapplink.iface.lib.PublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.add(builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder addPublicKey(
        int index, xyz.dapplink.iface.lib.PublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.add(index, builderForValue.build());
        onChanged();
      } else {
        publicKeyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder addAllPublicKey(
        java.lang.Iterable<? extends xyz.dapplink.iface.lib.PublicKey> values) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publicKey_);
        onChanged();
      } else {
        publicKeyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder clearPublicKey() {
      if (publicKeyBuilder_ == null) {
        publicKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        publicKeyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public Builder removePublicKey(int index) {
      if (publicKeyBuilder_ == null) {
        ensurePublicKeyIsMutable();
        publicKey_.remove(index);
        onChanged();
      } else {
        publicKeyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public xyz.dapplink.iface.lib.PublicKey.Builder getPublicKeyBuilder(
        int index) {
      return getPublicKeyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public xyz.dapplink.iface.lib.PublicKeyOrBuilder getPublicKeyOrBuilder(
        int index) {
      if (publicKeyBuilder_ == null) {
        return publicKey_.get(index);  } else {
        return publicKeyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public java.util.List<? extends xyz.dapplink.iface.lib.PublicKeyOrBuilder> 
         getPublicKeyOrBuilderList() {
      if (publicKeyBuilder_ != null) {
        return publicKeyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(publicKey_);
      }
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public xyz.dapplink.iface.lib.PublicKey.Builder addPublicKeyBuilder() {
      return getPublicKeyFieldBuilder().addBuilder(
          xyz.dapplink.iface.lib.PublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public xyz.dapplink.iface.lib.PublicKey.Builder addPublicKeyBuilder(
        int index) {
      return getPublicKeyFieldBuilder().addBuilder(
          index, xyz.dapplink.iface.lib.PublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
     */
    public java.util.List<xyz.dapplink.iface.lib.PublicKey.Builder> 
         getPublicKeyBuilderList() {
      return getPublicKeyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        xyz.dapplink.iface.lib.PublicKey, xyz.dapplink.iface.lib.PublicKey.Builder, xyz.dapplink.iface.lib.PublicKeyOrBuilder> 
        getPublicKeyFieldBuilder() {
      if (publicKeyBuilder_ == null) {
        publicKeyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            xyz.dapplink.iface.lib.PublicKey, xyz.dapplink.iface.lib.PublicKey.Builder, xyz.dapplink.iface.lib.PublicKeyOrBuilder>(
                publicKey_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        publicKey_ = null;
      }
      return publicKeyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dapplink.wallet.ExportPublicKeyResponse)
  }

  // @@protoc_insertion_point(class_scope:dapplink.wallet.ExportPublicKeyResponse)
  private static final xyz.dapplink.iface.lib.ExportPublicKeyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new xyz.dapplink.iface.lib.ExportPublicKeyResponse();
  }

  public static xyz.dapplink.iface.lib.ExportPublicKeyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportPublicKeyResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExportPublicKeyResponse>() {
    @java.lang.Override
    public ExportPublicKeyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExportPublicKeyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExportPublicKeyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public xyz.dapplink.iface.lib.ExportPublicKeyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

