// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public interface ExportPublicKeyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dapplink.wallet.ExportPublicKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  java.util.List<xyz.dapplink.iface.lib.PublicKey> 
      getPublicKeyList();
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  xyz.dapplink.iface.lib.PublicKey getPublicKey(int index);
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  int getPublicKeyCount();
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  java.util.List<? extends xyz.dapplink.iface.lib.PublicKeyOrBuilder> 
      getPublicKeyOrBuilderList();
  /**
   * <code>repeated .dapplink.wallet.PublicKey public_key = 3;</code>
   */
  xyz.dapplink.iface.lib.PublicKeyOrBuilder getPublicKeyOrBuilder(
      int index);
}
