// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

/**
 * Protobuf type {@code GenerateKeygenResponse}
 */
public final class GenerateKeygenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GenerateKeygenResponse)
    GenerateKeygenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateKeygenResponse.newBuilder() to construct.
  private GenerateKeygenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateKeygenResponse() {
    publicKeyList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenerateKeygenResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return xyz.dapplink.iface.lib.AccountProto.internal_static_GenerateKeygenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return xyz.dapplink.iface.lib.AccountProto.internal_static_GenerateKeygenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            xyz.dapplink.iface.lib.GenerateKeygenResponse.class, xyz.dapplink.iface.lib.GenerateKeygenResponse.Builder.class);
  }

  public static final int PUBLICKEYLIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList publicKeyList_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @return A list containing the publicKeyList.
   */
  public com.google.protobuf.ProtocolStringList
      getPublicKeyListList() {
    return publicKeyList_;
  }
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @return The count of publicKeyList.
   */
  public int getPublicKeyListCount() {
    return publicKeyList_.size();
  }
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @param index The index of the element to return.
   * @return The publicKeyList at the given index.
   */
  public java.lang.String getPublicKeyList(int index) {
    return publicKeyList_.get(index);
  }
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the publicKeyList at the given index.
   */
  public com.google.protobuf.ByteString
      getPublicKeyListBytes(int index) {
    return publicKeyList_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < publicKeyList_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, publicKeyList_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < publicKeyList_.size(); i++) {
        dataSize += computeStringSizeNoTag(publicKeyList_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPublicKeyListList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof xyz.dapplink.iface.lib.GenerateKeygenResponse)) {
      return super.equals(obj);
    }
    xyz.dapplink.iface.lib.GenerateKeygenResponse other = (xyz.dapplink.iface.lib.GenerateKeygenResponse) obj;

    if (!getPublicKeyListList()
        .equals(other.getPublicKeyListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPublicKeyListCount() > 0) {
      hash = (37 * hash) + PUBLICKEYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKeyListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static xyz.dapplink.iface.lib.GenerateKeygenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(xyz.dapplink.iface.lib.GenerateKeygenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GenerateKeygenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GenerateKeygenResponse)
      xyz.dapplink.iface.lib.GenerateKeygenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.dapplink.iface.lib.AccountProto.internal_static_GenerateKeygenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.dapplink.iface.lib.AccountProto.internal_static_GenerateKeygenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.dapplink.iface.lib.GenerateKeygenResponse.class, xyz.dapplink.iface.lib.GenerateKeygenResponse.Builder.class);
    }

    // Construct using xyz.dapplink.iface.lib.GenerateKeygenResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      publicKeyList_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return xyz.dapplink.iface.lib.AccountProto.internal_static_GenerateKeygenResponse_descriptor;
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.GenerateKeygenResponse getDefaultInstanceForType() {
      return xyz.dapplink.iface.lib.GenerateKeygenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.GenerateKeygenResponse build() {
      xyz.dapplink.iface.lib.GenerateKeygenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public xyz.dapplink.iface.lib.GenerateKeygenResponse buildPartial() {
      xyz.dapplink.iface.lib.GenerateKeygenResponse result = new xyz.dapplink.iface.lib.GenerateKeygenResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(xyz.dapplink.iface.lib.GenerateKeygenResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        publicKeyList_.makeImmutable();
        result.publicKeyList_ = publicKeyList_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof xyz.dapplink.iface.lib.GenerateKeygenResponse) {
        return mergeFrom((xyz.dapplink.iface.lib.GenerateKeygenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(xyz.dapplink.iface.lib.GenerateKeygenResponse other) {
      if (other == xyz.dapplink.iface.lib.GenerateKeygenResponse.getDefaultInstance()) return this;
      if (!other.publicKeyList_.isEmpty()) {
        if (publicKeyList_.isEmpty()) {
          publicKeyList_ = other.publicKeyList_;
          bitField0_ |= 0x00000001;
        } else {
          ensurePublicKeyListIsMutable();
          publicKeyList_.addAll(other.publicKeyList_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePublicKeyListIsMutable();
              publicKeyList_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList publicKeyList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePublicKeyListIsMutable() {
      if (!publicKeyList_.isModifiable()) {
        publicKeyList_ = new com.google.protobuf.LazyStringArrayList(publicKeyList_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @return A list containing the publicKeyList.
     */
    public com.google.protobuf.ProtocolStringList
        getPublicKeyListList() {
      publicKeyList_.makeImmutable();
      return publicKeyList_;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @return The count of publicKeyList.
     */
    public int getPublicKeyListCount() {
      return publicKeyList_.size();
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param index The index of the element to return.
     * @return The publicKeyList at the given index.
     */
    public java.lang.String getPublicKeyList(int index) {
      return publicKeyList_.get(index);
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publicKeyList at the given index.
     */
    public com.google.protobuf.ByteString
        getPublicKeyListBytes(int index) {
      return publicKeyList_.getByteString(index);
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param index The index to set the value at.
     * @param value The publicKeyList to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKeyList(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePublicKeyListIsMutable();
      publicKeyList_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param value The publicKeyList to add.
     * @return This builder for chaining.
     */
    public Builder addPublicKeyList(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePublicKeyListIsMutable();
      publicKeyList_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param values The publicKeyList to add.
     * @return This builder for chaining.
     */
    public Builder addAllPublicKeyList(
        java.lang.Iterable<java.lang.String> values) {
      ensurePublicKeyListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, publicKeyList_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKeyList() {
      publicKeyList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string publicKeyList = 1;</code>
     * @param value The bytes of the publicKeyList to add.
     * @return This builder for chaining.
     */
    public Builder addPublicKeyListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePublicKeyListIsMutable();
      publicKeyList_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GenerateKeygenResponse)
  }

  // @@protoc_insertion_point(class_scope:GenerateKeygenResponse)
  private static final xyz.dapplink.iface.lib.GenerateKeygenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new xyz.dapplink.iface.lib.GenerateKeygenResponse();
  }

  public static xyz.dapplink.iface.lib.GenerateKeygenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateKeygenResponse>
      PARSER = new com.google.protobuf.AbstractParser<GenerateKeygenResponse>() {
    @java.lang.Override
    public GenerateKeygenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GenerateKeygenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateKeygenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public xyz.dapplink.iface.lib.GenerateKeygenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

