// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

public interface GenerateSignatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateSignatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string publicKey = 1;</code>
   * @return The publicKey.
   */
  java.lang.String getPublicKey();
  /**
   * <code>string publicKey = 1;</code>
   * @return The bytes for publicKey.
   */
  com.google.protobuf.ByteString
      getPublicKeyBytes();
}
