// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

public interface GenerateSignatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateSignatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signature = 1;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 1;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
