// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

public interface GenerateKeygenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateKeygenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @return A list containing the publicKeyList.
   */
  java.util.List<java.lang.String>
      getPublicKeyListList();
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @return The count of publicKeyList.
   */
  int getPublicKeyListCount();
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @param index The index of the element to return.
   * @return The publicKeyList at the given index.
   */
  java.lang.String getPublicKeyList(int index);
  /**
   * <code>repeated string publicKeyList = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the publicKeyList at the given index.
   */
  com.google.protobuf.ByteString
      getPublicKeyListBytes(int index);
}
