// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package xyz.dapplink.iface.lib;

public interface GenerateKeygenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenerateKeygenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 number = 1;</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();
}
