// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public interface PublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dapplink.wallet.PublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string compress_pubkey = 1;</code>
   * @return The compressPubkey.
   */
  java.lang.String getCompressPubkey();
  /**
   * <code>string compress_pubkey = 1;</code>
   * @return The bytes for compressPubkey.
   */
  com.google.protobuf.ByteString
      getCompressPubkeyBytes();

  /**
   * <code>string decompress_pubkey = 2;</code>
   * @return The decompressPubkey.
   */
  java.lang.String getDecompressPubkey();
  /**
   * <code>string decompress_pubkey = 2;</code>
   * @return The bytes for decompressPubkey.
   */
  com.google.protobuf.ByteString
      getDecompressPubkeyBytes();
}
