// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public interface SignTxMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dapplink.wallet.SignTxMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string signature = 3;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 3;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
