// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public interface SignTxMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dapplink.wallet.SignTxMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string consumer_token = 1;</code>
   * @return The consumerToken.
   */
  java.lang.String getConsumerToken();
  /**
   * <code>string consumer_token = 1;</code>
   * @return The bytes for consumerToken.
   */
  com.google.protobuf.ByteString
      getConsumerTokenBytes();

  /**
   * <code>string public_key = 2;</code>
   * @return The publicKey.
   */
  java.lang.String getPublicKey();
  /**
   * <code>string public_key = 2;</code>
   * @return The bytes for publicKey.
   */
  com.google.protobuf.ByteString
      getPublicKeyBytes();

  /**
   * <code>string message_hash = 3;</code>
   * @return The messageHash.
   */
  java.lang.String getMessageHash();
  /**
   * <code>string message_hash = 3;</code>
   * @return The bytes for messageHash.
   */
  com.google.protobuf.ByteString
      getMessageHashBytes();
}
