// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package xyz.dapplink.iface.lib;

public final class WalletProto {
  private WalletProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_PublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_SupportSignWayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_SupportSignWayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_SupportSignWayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_SupportSignWayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_ExportPublicKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_ExportPublicKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_ExportPublicKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_SignTxMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_SignTxMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dapplink_wallet_SignTxMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dapplink_wallet_SignTxMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014wallet.proto\022\017dapplink.wallet\"?\n\tPubli" +
      "cKey\022\027\n\017compress_pubkey\030\001 \001(\t\022\031\n\021decompr" +
      "ess_pubkey\030\002 \001(\t\"=\n\025SupportSignWayReques" +
      "t\022\026\n\016consumer_token\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\"" +
      "D\n\026SupportSignWayResponse\022\014\n\004code\030\001 \001(\t\022" +
      "\013\n\003msg\030\002 \001(\t\022\017\n\007support\030\003 \001(\010\"N\n\026ExportP" +
      "ublicKeyRequest\022\026\n\016consumer_token\030\001 \001(\t\022" +
      "\014\n\004type\030\002 \001(\t\022\016\n\006number\030\003 \001(\004\"d\n\027ExportP" +
      "ublicKeyResponse\022\014\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 " +
      "\001(\t\022.\n\npublic_key\030\003 \003(\0132\032.dapplink.walle" +
      "t.PublicKey\"X\n\024SignTxMessageRequest\022\026\n\016c" +
      "onsumer_token\030\001 \001(\t\022\022\n\npublic_key\030\002 \001(\t\022" +
      "\024\n\014message_hash\030\003 \001(\t\"E\n\025SignTxMessageRe" +
      "sponse\022\014\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\021\n\tsig" +
      "nature\030\003 \001(\t2\305\002\n\rWalletService\022f\n\021getSup" +
      "portSignWay\022&.dapplink.wallet.SupportSig" +
      "nWayRequest\032\'.dapplink.wallet.SupportSig" +
      "nWayResponse\"\000\022j\n\023exportPublicKeyList\022\'." +
      "dapplink.wallet.ExportPublicKeyRequest\032(" +
      ".dapplink.wallet.ExportPublicKeyResponse" +
      "\"\000\022`\n\rsignTxMessage\022%.dapplink.wallet.Si" +
      "gnTxMessageRequest\032&.dapplink.wallet.Sig" +
      "nTxMessageResponse\"\000B\'\n\026xyz.dapplink.ifa" +
      "ce.libB\013WalletProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dapplink_wallet_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dapplink_wallet_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_PublicKey_descriptor,
        new java.lang.String[] { "CompressPubkey", "DecompressPubkey", });
    internal_static_dapplink_wallet_SupportSignWayRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dapplink_wallet_SupportSignWayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_SupportSignWayRequest_descriptor,
        new java.lang.String[] { "ConsumerToken", "Type", });
    internal_static_dapplink_wallet_SupportSignWayResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dapplink_wallet_SupportSignWayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_SupportSignWayResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "Support", });
    internal_static_dapplink_wallet_ExportPublicKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dapplink_wallet_ExportPublicKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_ExportPublicKeyRequest_descriptor,
        new java.lang.String[] { "ConsumerToken", "Type", "Number", });
    internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dapplink_wallet_ExportPublicKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_ExportPublicKeyResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "PublicKey", });
    internal_static_dapplink_wallet_SignTxMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dapplink_wallet_SignTxMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_SignTxMessageRequest_descriptor,
        new java.lang.String[] { "ConsumerToken", "PublicKey", "MessageHash", });
    internal_static_dapplink_wallet_SignTxMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_dapplink_wallet_SignTxMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dapplink_wallet_SignTxMessageResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
